#! /bin/sh

sxhkd &

bspc monitor -d I II III IV

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.66
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Transmission-gtk pseudo_tiled=on
bspc rule -a feh floating=on manage=off

feh --randomize --bg-fill --no-fehbg $HOME/Pictures/wallpapers/* 

